"""initial migration

Revision ID: 2dfb29cf4ae3
Revises: 
Create Date: 2025-04-08 18:49:50.844970

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = '2dfb29cf4ae3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('members',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(100), nullable=True),
        sa.Column('phone_number', sa.String(20), unique=True, nullable=False),
        sa.Column('points', sa.Float(), default=0.0),
        sa.Column('created_at', sa.DateTime(), nullable=False)
    )
    op.create_table('sale',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('member_id', sa.Integer(), nullable=True),
        sa.Column('total_price', sa.Float(), nullable=True),
        sa.Column('member_status', sa.String(25), nullable=True),
        sa.Column('created_by', sa.String(50), nullable=False),
        sa.Column('created_at', sa.Date, default=date.today),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    )
    op.create_table('sale_details',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('sale_id', sa.Integer(), sa.ForeignKey('sale.id', ondelete='CASCADE')),
        sa.Column('member_id', sa.Integer(), sa.ForeignKey('members.id', ondelete='CASCADE'), nullable=True),
        sa.Column('member_since', sa.Date, nullable=True),
        sa.Column('member_point', sa.Float(), nullable=True),
        sa.Column('invoice', sa.String(25), nullable=False),
        sa.Column('product_name', sa.String(100), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('product_price', sa.Float(), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=True),
        sa.Column('total_pay', sa.Float(), nullable=True),
        sa.Column('used_point', sa.Float(), nullable=True),
        sa.Column('refund', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_details')
    op.drop_table('sale')
    op.drop_table('members')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
